import uuid
from datetime import datetime
from fastapi import APIRouter, Depends
from auth.dependencies import get_current_user
from models import User, Report
from database import get_db
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from services.storage_service import StorageService

router = APIRouter()

@router.get("")
async def list_reports(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """List all generated reports for the client."""
    result = await db.execute(
        select(Report).where(Report.client_id == current_user.client_id).order_by(Report.created_at.desc())
    )
    reports = result.scalars().all()
    
    storage = StorageService()
    
    output = []
    for r in reports:
        download_url = r.download_url
        if download_url and not download_url.startswith("http"):
            download_url = storage.generate_download_url(download_url)
            
        output.append({
            "id": str(r.id),
            "name": r.name,
            "type": r.type,
            "download_url": download_url,
            "created_at": r.created_at.isoformat() if r.created_at else None,
        })
    return output


@router.post("/generate")
async def generate_report(
    report_type: str = "monthly",
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Trigger report generation (PDF). Returns download URL when ready."""
    from fpdf import FPDF
    
    # 1. Generate PDF using fpdf2
    report_name = f"{report_type.capitalize()} Performance Report - {datetime.utcnow().strftime('%B %Y')}"
    
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("helvetica", size=24)
    pdf.cell(200, 20, text="LitLabs Performance Report", new_x="LMARGIN", new_y="NEXT", align='C')
    
    pdf.set_font("helvetica", size=16)
    pdf.cell(200, 15, text=report_name, new_x="LMARGIN", new_y="NEXT", align='C')
    
    pdf.set_font("helvetica", size=12)
    pdf.cell(200, 10, text=f"Prepared for Client ID: {current_user.client_id}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(200, 10, text="This is a dynamically generated report detailing your recent performance metrics,", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(200, 10, text="growth trends, and strategic insights.", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_y(260)
    pdf.set_font("helvetica", size=8)
    pdf.cell(200, 10, text=f"Generated by LitLabs Client Dashboard on {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')}", new_x="LMARGIN", new_y="NEXT", align='C')
    
    pdf_bytes = pdf.output()

    
    # 3. Upload to MinIO
    storage = StorageService()
    filename = f"report_{report_type}_{int(datetime.utcnow().timestamp())}.pdf"
    object_key = storage.upload_pdf_bytes(str(current_user.client_id), filename, pdf_bytes)
    
    # 4. Save Report record in DB
    report = Report(
        client_id=current_user.client_id,
        name=report_name,
        type=report_type,
        download_url=object_key
    )
    db.add(report)
    await db.commit()
    await db.refresh(report)
    
    download_url = storage.generate_download_url(object_key)
    
    return {
        "status": "completed", 
        "message": "Report generated successfully.",
        "report_id": str(report.id),
        "download_url": download_url
    }
